--- #YAML:1.0
name:               Net-PicApp
version:            0.2
abstract:           A library for interfacing with the PicApp service.
author:
    - Byrne Reese <byrne@majordojo.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
